# Generated by Django 3.2.8 on 2021-10-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='slug',
        ),
    ]
